security:
    # Gestion du hash des mots de passe
    password_hashers:
        App\Entity\User:
            algorithm: auto

    # Déclaration du provider (utilise ton entité User)
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Configuration du pare-feu principal
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator:
                - App\Security\AppAuthenticator
                - App\Security\GitStatusAuthenticator
            logout:
                path: app_logout
                # où rediriger après déconnexion (facultatif)
                # target: app_home

    # Règles d’accès
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            App\Entity\User:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10