services:
  - type: web
    name: canopees-api
    env: php
    plan: free
    region: frankfurt
    buildCommand: "composer install --no-dev --optimize-autoloader"
    startCommand: "php -S 0.0.0.0:10000 -t public"
    envVars:
      - key: APP_ENV
        value: prod